// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Deal struct {
	ID              int64 `json:"deal_id"`
	PitchID         sql.NullInt64 `json:"pitch_id"`
	SalesRepName    string `json:"sales_rep_name"`
	CustomerName    string `json:"customer_name"`
	ServiceToRender []string `json:"services_to_render"`
	// it is either ongoing or closed
	Status string 	`json:"deal_status"`
	// tag for the status can be, working on: survey, proposal, costing depending
	StatusTag           string `json:"department"`
	CurrentPitchRequest string 	`json:"current_pitch_request"`
	NetTotalCost        string `json:"net_total_cost"`
	Profit              string `json:"profit"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time 	`json:"updated_at"`
	ClosedAt            time.Time 	`json:"closed_at"`
	Awarded             bool `json:"awarded"`
}

type PitchRequest struct {
	ID              int64 `json:"pitch_id"`
	SalesRepID      int64 	`json:"sales_rep_id"`
	SalesRepName    string `json:"sales_rep_name"`
	Status          string `json:"status"`
	CustomerName    string `json:"customer_name"`
	PitchTag        string `json:"department"`
	CustomerRequest []string `json:"customer_request"`
	RequestDeadline time.Time `json:"request_deadline"`
	AdminViewed     bool `json:"admin_viewed"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type User struct {
	ID       int64 `json:"user_id"`
	Username string `json:"username"`
	// Role of the user, e.g., sales rep, admin, manager
	Role            string `json:"role"`
	FullName        string `json:"fullname"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	PasswordChanged bool `json:"password_changed"`
	UpdatedAt       time.Time `json:"updated_at"`
	CreatedAt       time.Time `json:"created_at"`
}
