// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, role, full_name, email, password)
VALUES ( $1, $2, $3, $4, $5)
RETURNING users.id
`

type CreateUserParams struct {
	Username string `json:"username"`
	Role     string `json:"role"`
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Role,
		arg.FullName,
		arg.Email,
		arg.Password,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNumberOfAdminUsers = `-- name: GetNumberOfAdminUsers :one
SELECT COUNT(*) FROM users WHERE role = $1
`

func (q *Queries) GetNumberOfAdminUsers(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, getNumberOfAdminUsers, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalNumberOfUsers = `-- name: GetTotalNumberOfUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) GetTotalNumberOfUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalNumberOfUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, role, full_name, email, password, password_changed, updated_at, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.PasswordChanged,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT 
    id AS user_id,
    username,
    role,
    email,
    full_name,
    password_changed,
    to_char(updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS updated_at,
    to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS created_at
FROM users
LIMIT $1
OFFSET $2
`

type ListAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllUsersRow struct {
	UserID          int64  `json:"user_id"`
	Username        string `json:"username"`
	Role            string `json:"role"`
	Email           string `json:"email"`
	FullName        string `json:"full_name"`
	PasswordChanged bool   `json:"password_changed"`
	UpdatedAt       string `json:"updated_at"`
	CreatedAt       string `json:"created_at"`
}

func (q *Queries) ListAllUsers(ctx context.Context, arg ListAllUsersParams) ([]ListAllUsersRow, error) {
	rows, err := q.db.Query(ctx, listAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUsersRow{}
	for rows.Next() {
		var i ListAllUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.FullName,
			&i.PasswordChanged,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testGetUserPaginated = `-- name: TestGetUserPaginated :many
WITH user_data AS (
    SELECT 
        id as user_id,
        username,
        role,
        email,
        full_name,
        password_changed,
        to_char(updated_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS updated_at,
        to_char(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS created_at
    FROM users
    ORDER BY id
    LIMIT $1 OFFSET $2
)
SELECT 
    (SELECT COUNT(*) FROM users) AS total_users,
    json_agg(user_data) AS users
FROM user_data
`

type TestGetUserPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type TestGetUserPaginatedRow struct {
	TotalUsers int64  `json:"total_users"`
	Users      []byte `json:"users"`
}

func (q *Queries) TestGetUserPaginated(ctx context.Context, arg TestGetUserPaginatedParams) ([]TestGetUserPaginatedRow, error) {
	rows, err := q.db.Query(ctx, testGetUserPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestGetUserPaginatedRow{}
	for rows.Next() {
		var i TestGetUserPaginatedRow
		if err := rows.Scan(&i.TotalUsers, &i.Users); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users 
 SET username = $2, full_name = $3, role = $4, email = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	FullName string `json:"full_name"`
	Role     string `json:"role"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.Email,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
 SET password = $2, password_changed = $3
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID              int64  `json:"id"`
	Password        string `json:"password"`
	PasswordChanged bool   `json:"password_changed"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password, arg.PasswordChanged)
	return err
}
