name: "pre-sales-deal-tracker"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=vasDealTracker
      - POSTGRES_DB=dealTrackerDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://root:vasDealTracker@db:5432/dealTrackerDB?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    command: ["/app/main"]

volumes:
  pgdata:
