services:
  postgres:
    image: postgres:17-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=vasDealTracker
      - POSTGRES_DB=dealTrackerDB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dealTrackerDB"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 45s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_SOURCE=postgresql://root:vasDealTracker@postgres:5432/dealTrackerDB?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    command: [ "/app/main" ]