swagger: '2.0'
info:
  description: Custom API for pre-sales deal tracker
  version: 1.0.0
  title: API Endpoints for Pre-sales Deal Tracker
host: 'localhost:8080' #yet to be set or use localhost :)
basePath: /
tags: []
schemes:
  - http
  - https
paths:
  /users:
    post:
      # tags:
      #   - Create User
      summary: 'Admin creates a new user'
      description: ''
      operationId: adminCreateUser
      produces:
        - application/json
      parameters:
        - name: CreateUsrReq
          in: body
          description: The user object to create
          required: true
          schema:
            $ref: '#/definitions/CreateUsrReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CreateUsrResp'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp'
  /users/login:
    post:
      # tags:
      #   - User Login
      summary: To login user
      description: ''
      operationId: userLogin
      produces:
        - application/json
      parameters:
        - name: LoginReq
          in: body
          description: An object holding user's username and password
          required: true
          schema:
            $ref: '#/definitions/LoginReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/LoginResp'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '401':
          description: unauthorized operation or wrong password
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp'         
  /sales/pitchReq:
    post:
      # tags:
      #   - Create Pitch Request
      summary: Creates a (customer) pitch request
      description: ''
      operationId: salesCreatePitchReq
      produces:
        - application/json
      parameters:
        - name: PitchReq
          in: body
          description: An object holding fields needed to create a customer (pitch) request
          required: true
          schema:
            $ref: '#/definitions/PitchReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PitchResp'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '401':
          description: unauthorized operation
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp'
  /admin/deals:
    post:
      # tags:
      #   - Create a deal
      summary: Creates a deal based on a pitch request
      description: ''
      operationId: adminCreateDeal
      produces: 
        - application/json
      parameters:
        - name: CreateDealReq
          in: body
          description: An object holding the pitch request id from which a deal will be created
          required: true
          schema:
            $ref: '#/definitions/CreateDealReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/successMsg'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '401':
          description: unauthorized operation
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp'
  /deal/vas:
    get:
      # tags:
      #   - Get Deals with Status:ongoing
      summary: Get all deals with an ongoing status
      description: ''
      operationId: getOngoingDeals
      produces: 
        - 'application/json'
      parameters:
        - name: status
          in: query
          description: current deal status
          required: true
          type: string
      responses:
        '200':
          description: successful request
          schema:
            type: array
            items:
              $ref: '#/definitions/CreateDealResp'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '401':
          description: unauthorized access
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp'
  /deals/filtered:
    get:
      # tags:
      #   - Get deals filtered by request
      summary: Get deals that meet the request filter requirements
      description: ''
      operationId: getFilteredDeals
      produces:
        - 'application/json'
      parameters:
        - name: customer_name
          in: query
          description: deals having this customer name
          required: false
          type: string
        - name: service_to_render
          in: query
          description: deals having these/this service(s)
          required: false
          type: array
          items: {
            type: string
          }
        - name: status
          in: query
          description: deals having this status
          required: false
          type: string
        - name: max_profit
          in: query
          description: deals having this max_profit
          required: false
          type: string
        - name: min_profit
          in: query
          description: deals having this min_profit
          required: false
          type: string
        - name: awarded
          in: query
          description: deals awarded
          required: false
          type: boolean
        - name: sales_rep_name
          in: query
          description: deals having this sales_rep_name
          required: false
          type: string
        - name: page_size
          in: query
          description: The number of deals to return per page (used for pagination). Defines how many results to display in a single response.
          required: true
          type: integer
        - name: page_id
          in: query
          description: The page number or offset from which to start retrieving deals. Determines where the current page of results starts in the overal list.
          required: true
          type: integer
      responses:
        '200':
          description: successful request
          schema:
            type: array
            items:
              $ref: '#/definitions/CreateDealResp'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '401':
          description: unauthorized access
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp' 
  # /admin/pitchrequest:
  # /sales/pitchrequest:
  # /admin/getdeal:
  # /sales/deals:
  # /list-users:
  # /users/password-reset:
  # /admin/deal/update:
  # /users/update:
  # /users/password:
  # /pitchrequest/update:
  # /users/delete/:id:
  # /admin/deals/delete/:deal_id:
  # /sales/pitchReq/delete/:sales_username:sales_rep_id/:pitch_id:
definitions:
  errorResp:
      type: object
      properties:
        error:
          type: string
  successMsg:
    type: object
    properties:
      message:
        type: string
  CreateUsrReq:
    type: object
    properties:
      username:
        type: string
      role:
        type: string
      fullname:
        type: string
      email:
        type: string
      password:
        type: string
  CreateUsrResp:
    type: object
    properties:
      username:
        type: string
      role:
        type: string
      createdAt:
        type: integer
        description: unix time representation
  LoginReq:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  LoginResp:
    type: object
    properties:
      user_id:
        type: integer
      username:
        type: string
      role:
        type: string
      fullname:
        type: string
      email:
        type: string
      updated_at:
        type: integer
      created_at:
        type: integer
  PitchReq:
    type: object
    properties:
      sales_rep_id:
        type: integer
      sales_rep_name:
        type: string
      status:
        type: string
      customer_name:
        type: string
      pitch_tag:
        type: string
      customer_requests:
        type: array
        items: {
          type: string
        }       
      request_deadline:
        type: integer
  PitchResp:
    type: object
    properties:
      pitch_request_id:
        type: integer
      sales_rep_id:
        type: integer
      sales_rep_name:
        type: string
      status:
        type: string
      customer_name:
        type: string
      pitch_tag:
        type: string
      customer_requests:
        type: array
        items: {
          type: string
        }
      request_deadline:
        type: integer
      admin_viewed: 
        type: boolean
      created_at:
        type: integer
      updated_at:
        type: integer
  CreateDealReq:
    type: object
    properties:
      pitch_id:
        type: integer
  CreateDealResp:
    type: object
    properties:
      id:
        type: integer
      pitch_id:
        type: integer
      sales_rep_name:
        type: string
      customer_name:
        type: string
      service_to_render:
        type: array
        items: {
          type: string
        }
      status:
        type: string
      status_tag:
        type: string
      current_pitch_request:
        type: string
      net_total_cost:
        type: string
      profit:
        type: string
      created_at:
        type: integer
      updated_at:
        type: integer
      closed_at:
        type: integer
      awarded:
        type: boolean
