swagger: '2.0'
info:
  description: Custom API for pre-sales deal tracker
  version: 1.0.0
  title: API Endpoints for Pre-sales Deal Tracker
host: 'localhost:8080' #yet to be set or use localhost :)
basePath: /
tags: []
schemes:
  - http
  - https
paths:
  /users:
    post:
      tags:
        - Create User
      summary: 'Admin creates a new user'
      description: ''
      operationId: adminCreateUser
      produces:
        - application/json
      parameters:
        - name: CreateUsrReq
          in: body
          description: The user object to create
          required: true
          schema:
            $ref: '#/definitions/CreateUsrReq'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/CreateUsrResp'
        '400':
          description: bad request
          schema:
            $ref: '#/definitions/errorResp'
        '500':
          description: server error
          schema:
            $ref: '#/definitions/errorResp'
  # /users/login:
  # /sales/pitchReq:
  # /admin/deals:
  # /deals/filtered:
  # /admin/pitchrequest:
  # /sales/pitchrequest:
  # /admin/getdeal:
  # /sales/deals:
  # /users:
  # /users/password-reset:
  # /admin/deal/update:
  # /users/update:
  # /users/password:
  # /pitchrequest/update:
  # /users/delete/:id:
  # /admin/deals/delete/:deal_id:
  # /sales/pitchReq/delete/:sales_username:sales_rep_id/:pitch_id:
definitions:
  CreateUsrReq:
    type: object
    properties:
      username:
        type: string
      role:
        type: string
      fullname:
        type: string
      email:
        type: string
      password:
        type: string
  CreateUsrResp:
    type: object
    properties:
      username:
        type: string
      role:
        type: string
      createdAt:
        type: integer
        description: unix time representation
  errorResp:
    type: object
    properties:
      error:
        type: string
  