// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"
)

const authLogin = `-- name: AuthLogin :one
SELECT id, username, role, full_name, email, password, password_changed, updated_at, created_at FROM users
WHERE username = $1
LIMIT 1
`

// AuthLogin
//
//	SELECT id, username, role, full_name, email, password, password_changed, updated_at, created_at FROM users
//	WHERE username = $1
//	LIMIT 1
func (q *Queries) AuthLogin(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, authLogin, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.FullName,
		&i.Email,
		&i.Password,
		&i.PasswordChanged,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
