// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: deals.sql

package db

import (
	"context"
)

const updateDealSalesName = `-- name: UpdateDealSalesName :exec
UPDATE deals SET sales_rep_name = $1
`

func (q *Queries) UpdateDealSalesName(ctx context.Context, salesRepName string) error {
	_, err := q.db.Exec(ctx, updateDealSalesName, salesRepName)
	return err
}
