// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	//AuthLogin
	//
	//  SELECT id, username, role, full_name, email, password, password_changed, updated_at, created_at FROM users
	//  WHERE username = $1
	//  LIMIT 1
	AuthLogin(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
